# This is a basic workflow to help you get started with Actions

name: Check Secrets
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
 # pull_request:
 #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check secrets with the trufflehog
        run: |
          pip install truffleHog
          trufflehog --regex --json --rules=./rules/secrets-pattern.json --entropy=False ./ > check-secrets.log
      - name: Upload logs if fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with: 
          name: Check secrets log
          path: check-secrets.log
